package:
    name: eofs
    version: 1.1.0

source:
    git_url: git://github.com/ajdawson/eofs.git
    git_tag: v1.1.0

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    requires:
        - nose
        - pep8
    imports:
        - eofs

about:
    home: http://ajdawson.github.io/eofs/
    license: GPL v3
